/**
 * Litopia API
 * This is the Litopia API an apis made to manange player of litopia an lot more !
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MinecraftUserEntity } from './minecraftUserEntity';


export interface UserEntityMinecraftUser {
    minecraftUUID: string;
    minecraftNickname: string;
}

